In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch
import torch.nn as nn

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70],
                   [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69,96, 70],
                   [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]],dtype='float32')

In [3]:
X = torch.from_numpy(inputs)
y = torch.from_numpy(targets)

In [4]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [5]:
# Define dataset
train_ds = TensorDataset(X,y)
train_ds[0:5]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [6]:
# Define data loader
batch_size = 4
train_dl = DataLoader(train_ds,batch_size,shuffle=True)
next(iter(train_dl))

[tensor([[ 87., 134.,  58.],
         [ 73.,  67.,  43.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.]]), tensor([[119., 133.],
         [ 56.,  70.],
         [ 56.,  70.],
         [ 81., 101.]])]

In [7]:
# Define model
model = nn.Linear(3,2) #3 inputs and 2 outputs
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3603, -0.3317, -0.4886],
        [ 0.5240, -0.5172, -0.4044]], requires_grad=True)
Parameter containing:
tensor([-0.2164,  0.5748], requires_grad=True)


In [8]:
#Obtain Parameters
opt = torch.optim.SGD(model.parameters(),lr=1e-4)

In [9]:
# Import nn.functional
import torch.nn.functional as F

In [10]:
# Define loss function
loss_fn = F.mse_loss

In [11]:
# Calculate loss
loss = loss_fn(model(X),y)
print(loss)

tensor(22283.0957, grad_fn=<MseLossBackward0>)


In [12]:
#Obtain Parameters
opt = torch.optim.SGD(model.parameters(),lr=1e-4)

In [13]:
# Train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            #Generate Predictions
            pred = model(xb)
            loss = loss_fn(pred,yb)
            #Perform Gradient Descent
            loss.backward()
            opt.step()
            #set the gradients to zero
            opt.zero_grad()
        if (epoch+1) % 10 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {round(loss.item(), 3)} ,{xb} , {yb}')

In [14]:
# Train the model for 100 epochs
fit(100,model,loss_fn,opt, train_dl)

Epoch [10/100], Loss: 3.808 ,tensor([[ 87., 134.,  58.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]]) , tensor([[119., 133.],
        [119., 133.],
        [ 56.,  70.]])
Epoch [20/100], Loss: 193.114 ,tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]]) , tensor([[ 56.,  70.],
        [119., 133.],
        [ 81., 101.]])
Epoch [30/100], Loss: 6.13 ,tensor([[ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.]]) , tensor([[ 56.,  70.],
        [103., 119.],
        [ 22.,  37.]])
Epoch [40/100], Loss: 12.041 ,tensor([[ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.]]) , tensor([[119., 133.],
        [103., 119.],
        [ 81., 101.]])
Epoch [50/100], Loss: 2.892 ,tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.]]) , tensor([[ 56.,  70.],
        [ 81., 101.],
        [ 22.,  37.]])
Epoch [60/100], Loss: 5.646 ,tensor([[ 87., 134.,  58.],
        [ 73.,  67.,  43.]

In [15]:
# Generate predictions
preds = model(X)
preds

tensor([[ 57.9232,  70.6702],
        [ 83.1740, 100.8466],
        [120.2451, 133.4669],
        [ 21.7916,  37.3660],
        [102.7872, 119.2459],
        [ 57.9232,  70.6702],
        [ 83.1740, 100.8466],
        [120.2451, 133.4669],
        [ 21.7916,  37.3660],
        [102.7872, 119.2459],
        [ 57.9232,  70.6702],
        [ 83.1740, 100.8466],
        [120.2451, 133.4669],
        [ 21.7916,  37.3660],
        [102.7872, 119.2459]], grad_fn=<AddmmBackward0>)

In [16]:
# Compare with targets
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [17]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y.detach().numpy(),preds.detach().numpy()))

1.0949112


**Exercise**
1. Estimate the value of model parameters(weights and bias) and MSE Loss after training for 1000 epochs.

In [18]:
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], Loss: 1.227 ,tensor([[91., 88., 64.],
        [73., 67., 43.],
        [91., 88., 64.]]) , tensor([[ 81., 101.],
        [ 56.,  70.],
        [ 81., 101.]])
Epoch [20/1000], Loss: 0.24 ,tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.]]) , tensor([[ 22.,  37.],
        [103., 119.],
        [119., 133.]])
Epoch [30/1000], Loss: 0.769 ,tensor([[ 87., 134.,  58.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.]]) , tensor([[119., 133.],
        [119., 133.],
        [103., 119.]])
Epoch [40/1000], Loss: 1.702 ,tensor([[69., 96., 70.],
        [91., 88., 64.],
        [69., 96., 70.]]) , tensor([[103., 119.],
        [ 81., 101.],
        [103., 119.]])
Epoch [50/1000], Loss: 1.694 ,tensor([[102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 69.,  96.,  70.]]) , tensor([[ 22.,  37.],
        [ 81., 101.],
        [103., 119.]])
Epoch [60/1000], Loss: 5.15 ,tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 73.,

In [19]:
print("Model Weight: ", model.weight)
print("Model Bias: ", model.bias)

Model Weight:  Parameter containing:
tensor([[-0.3978,  0.8510,  0.6788],
        [-0.3042,  0.7953,  0.9070]], requires_grad=True)
Model Bias:  Parameter containing:
tensor([-0.2135,  0.5669], requires_grad=True)


In [20]:
print(mean_squared_error(y.detach().numpy(),preds.detach().numpy()))

1.0949112


2. Take the learning rate value as 0.1 and train the model. Write in brief the impact of this learning rate on the model.

In [21]:
model2 = nn.Linear(3,2)

print("\n", model2.weight)
print("\n", model2.bias)

opt2 = torch.optim.SGD(model2.parameters(), lr=0.1)

fit(250, model2, loss_fn, opt2, train_dl)
preds = model2(X)

print(preds)
print(y)


 Parameter containing:
tensor([[ 0.1085, -0.5063,  0.1551],
        [-0.0503, -0.4616, -0.3772]], requires_grad=True)

 Parameter containing:
tensor([-0.0197,  0.1997], requires_grad=True)
Epoch [10/250], Loss: nan ,tensor([[91., 88., 64.],
        [73., 67., 43.],
        [91., 88., 64.]]) , tensor([[ 81., 101.],
        [ 56.,  70.],
        [ 81., 101.]])
Epoch [20/250], Loss: nan ,tensor([[69., 96., 70.],
        [73., 67., 43.],
        [69., 96., 70.]]) , tensor([[103., 119.],
        [ 56.,  70.],
        [103., 119.]])
Epoch [30/250], Loss: nan ,tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.]]) , tensor([[ 81., 101.],
        [119., 133.],
        [ 22.,  37.]])
Epoch [40/250], Loss: nan ,tensor([[102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.]]) , tensor([[ 22.,  37.],
        [ 56.,  70.],
        [119., 133.]])
Epoch [50/250], Loss: nan ,tensor([[91., 88., 64.],
        [69., 96., 70.],
        [91., 88., 64.]]) ,

3. Take the learning rate value as 0.0000001 and train the model. Write in brief the impact of this learning rate on the model.

In [22]:
model3 = nn.Linear(3,2)

opt3 = torch.optim.SGD(model3.parameters(), lr=0.0000001)

fit(250, model3, loss_fn, opt3, train_dl)
preds = model3(X)

print(preds)
print(y)

Epoch [10/250], Loss: 11826.582 ,tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) , tensor([[103., 119.],
        [ 22.,  37.],
        [103., 119.]])
Epoch [20/250], Loss: 10178.39 ,tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]]) , tensor([[ 56.,  70.],
        [119., 133.],
        [ 56.,  70.]])
Epoch [30/250], Loss: 9420.645 ,tensor([[ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.]]) , tensor([[119., 133.],
        [ 81., 101.],
        [ 22.,  37.]])
Epoch [40/250], Loss: 10150.188 ,tensor([[ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.]]) , tensor([[119., 133.],
        [ 56.,  70.],
        [103., 119.]])
Epoch [50/250], Loss: 5033.649 ,tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.]]) , tensor([[ 81., 101.],
        [ 22.,  37.],
        [ 81., 101.]])
Epoch [60/250], Loss: 1459.286 ,tensor([[ 73.,  67.,  43.],
        

In [23]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y.detach().numpy(),preds.detach().numpy()))

689.8718


4. Use the model to predict crop yield for apples if temperature is 70, Rain is 34 and Humidity is 45.

In [24]:
preds = model(torch.FloatTensor([70,34,45]))
preds

tensor([31.4234, 47.1256], grad_fn=<AddBackward0>)