In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

**Training Data**

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype = 'float32')

In [3]:
# Target (apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


**Linear Regression Model(from Scratch)**

In [5]:
# Weights and biases
w = torch.randn(3, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(w)
print(b)

tensor([[ 1.4920],
        [-0.7833],
        [-0.3750]], requires_grad=True)
tensor([0.7872], requires_grad=True)


In [6]:
# Define the model
def model(x):
    return x @ w + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 41.0991],
        [ 43.6316],
        [  3.8829],
        [105.4154],
        [  2.2916]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


**Loss Function**

In [9]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
loss = mse(preds, targets)
print(loss)

tensor(6394.1377, grad_fn=<DivBackward0>)


**Compute Gradients**

In [11]:
# Compute gradients
loss.backward()

In [12]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 1.4920],
        [-0.7833],
        [-0.3750]], requires_grad=True)
tensor([[ -5177.5972],
        [-10317.4473],
        [ -5468.9316]])


In [13]:
# Gradients for bias
print(b)
print(b.grad)

tensor([0.7872], requires_grad=True)
tensor([-73.8718])


In [14]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0.],
        [0.],
        [0.]])
tensor([0.])


**Adjust weights and bias using gradient descent**

In [15]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 41.0991],
        [ 43.6316],
        [  3.8829],
        [105.4154],
        [  2.2916]], grad_fn=<AddBackward0>)


In [16]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(6394.1377, grad_fn=<DivBackward0>)


In [17]:
# Compute gradients
print(w.grad)
print(b.grad)

tensor([[0.],
        [0.],
        [0.]])
tensor([0.])


In [18]:
# Adjust weights and reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [19]:
print(w)
print(b)

tensor([[ 1.4920],
        [-0.7833],
        [-0.3750]], requires_grad=True)
tensor([0.7872], requires_grad=True)


In [20]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(6394.1377, grad_fn=<DivBackward0>)


**Train for multiple epochs**

In [21]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [22]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(369.5601, grad_fn=<DivBackward0>)


In [23]:
# Print predictions
preds

tensor([[ 63.5012],
        [ 82.0432],
        [108.8816],
        [ 56.7015],
        [ 81.0030]], grad_fn=<AddBackward0>)

In [24]:
# Print targets
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])